schema_version = "1.0.0"
id = "extranodes"
name = "ExtraNodes"
version = "1.0.0"
tagline = "ExtraNodes, Exciting New Nodes (for GeometryNodes)"
maintainer = "bd3d"
type = "add-on"
tags = ["Geometry Nodes","Node"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-2.0-or-later"]
website = "https://blenderartists.org/t/bd3d-free-tools-and-products"
copyright = ["2025 BD3D DIGITAL DESIGN"]
